name: production

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
     # --- Frontend (Vitest) ---
  frontend-tests:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./client   # all commands run inside client/

    steps:
      # ── check out the repository ──
      - name: Checkout repository
        uses: actions/checkout@v4

      # ── set up Node.js ──
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      # ── install dependencies from lock file ──
      - name: Install dependencies
        run: npm ci

      # ── run the test suite ──
      - name: Run frontend tests
        run: npm test
  
  # --- Backend (Jest) ---
  backend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server   # all commands run inside server
    
    steps:
      # ── check out the repository ──
      - name: Checkout repository
        uses: actions/checkout@v4

      # ── setup Node.js  ──
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: server/package-lock.json
      
      # ── install dependencies from lock file ──
      - name: Install dependencies
        run: npm ci
      
      # ── run the test suite ──
      - name: Run backend tests
        run: npm test

  deploy:
    runs-on: self-hosted
    needs: [frontend-tests, backend-tests]
    steps:
        - name: Deploy
          env:
           DB_USER : ${{ secrets.DB_USER}}
           DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
           DB_HOST: ${{ secrets.DB_HOST }}
           DB_PORT: ${{ secrets.DB_PORT }}
           DB_NAME: ${{ secrets.DB_NAME }}
           JWT_SECRET: ${{ secrets.JWT_SECRET }}
           PEPPER_SECRET: ${{ secrets.PEPPER_SECRET }}
          
          run: docker compose up -d --build

